### ISSUE TITLE
Console and IE 11

### ISSUE THREAD

**Issue by bogeorge** [better-js-logging/angular-logger2#2]
We are having an issue in IE 11 where logging is failing unless we are actually have the F12 Developer tools open.  After some digging, it looks like requireConsole & the noop function is intended to defend against this however it doesn't seem to be for us.  Is there a configuration option I might be missing or something else?

**Comment by bogeorge** [comment]
Note, I just ran the plunkr demo in IE11 (http://plnkr.co/edit/ZZVA5nmyKpEWxztchYMx?p=preview).  If developer tools aren't enabled the "Check the console" never shows which sort of suggests that the template never loaded.  I get that console isn't there in IE unless F12 tools are enabled but things should still continue on their normal path right?

**Comment by bbottema** [comment]
Correct, I'll look into it this weekend.

**Comment by bogeorge** [comment]
Thanks!  No rush on my part, I can wrap the LoggingConfig to set LogLeve.OFF when console is undefined for now.

**Comment by bbottema** [comment]
Can you please verify the problem is solved with 1.0.6?

**Comment by bogeorge** [comment]
Hey Benny, the new version did not fix my issues in IE.  After doing some more digging/debugging what I think I've discovered is that the line loggingFunc.apply(null, enhancedArguments); in logging.logger.ts is throwing an exception in IE.  The exception is "Invalid calling object".  I wrapped this in a try/catch to swallow the exceptions and then things worked. As I test I replaced the null with the console object and the errors went away.  I did that on a whim after looking at this stack overflow (https://stackoverflow.com/questions/8159233/typeerror-illegal-invocation-on-console-log-apply)

**Comment by bbottema** [comment]
Ohh yeah, I walking into that one before. Both that question+answer already got an upvote from me :D

I'll uphdate the library

**Comment by bogeorge** [comment]
Thanks.  Issues like this just remind me just how much I dislike IE.

**Comment by bbottema** [comment]
Though why would it work with the DevTools open, if the invocation of loggingFunc.apply was wrong? I'm a little confused now.

**Comment by bogeorge** [comment]
I'm unsure why it works with DevTools open too, doesn't make a lot of sense to me either.  The challenge is that to debug I need dev tools open but they fix it so I was just testing with alerts and try catches around it.

**Comment by bbottema** [comment]
Please verify 1.0.7 solves the issue.

**Comment by bogeorge** [comment]
Thanks!  I just tested with version 1.0.7 and it looks like everything is working in IE11 now.  Thanks again for all your help and such quick turnaround on everything.

**Comment by bbottema** [comment]
Thanks for your analyses, it was very helpful 👍
